### ISSUE TITLE
Snippets crash Gummi on OpenBSD

### ISSUE THREAD

**Issue by usermjs** [alexandervdm/gummi#145]
Use of any snippet immediately causes Gummi to crash on OpenBSD 6.7.  It doesn't matter if the snippet is called with tab or via a shortcut.

**Comment by alexandervdm** [comment]
I have reproduced this issue and found the cause. I send a message to the maintainer of the port so we can hopefully push a fix.

**Comment by mkilian** [comment]
I can reproduce the problem on -current, too, but at least in one case it did not occur, so it's not completely deterministic.

Alexander suggested in his mail to me to use ports gcc instead of base gcc, but that would be a last resort -- I'll try to build gummi with debugging enabled and to install some debug-* packages to get a useful backtrace and to find (and fix) the real cause.

**Comment by alexandervdm** [comment]
Have to agree with @mkilian here. I can't explain why this bug would be non-deterministic - provided the input is constant - but I am not well acquainted with this particular component of Gummi. 

I believe a705dfc2009dc1a43907d28be13ceefde74252c5 fixes the issue. If you can confirm I will create a new release momentarily.

**Comment by alexandervdm** [comment]
Works for me, please re-open if the patch above or the release I'm about to build does not solve the issue.
