### ISSUE TITLE
Go to corresponding source code from PDF preview

### ISSUE THREAD

**Issue by leminhman0312** [alexandervdm/gummi#152]
Is this feature currently implemented in Gummi? Or is it going to be implemented in the future?

**Comment by Vectornaut** [comment]
I'd appreciate this feature too! I looked for SyncTeX-based implementations and found four we could copy from. I've sorted them by their similarities to Gummi. All four, like Gummi, use Poppler for PDF rendering.

- **Integrated PDF viewers from TeX editors** *(unlike Gummi, these have Qt interfaces)*
  - Texmaker: [`PdfViewer`](https://github.com/tdauth/texmaker/blob/b66e9479e2729c687a0921914a87d8d5dd3489be/pdfviewer.cpp)
  - TeXstudio: [`PDFDocument`](https://github.com/texstudio-org/texstudio/blob/78ef1555f5bf9aaf0784f66cd82ef983fde898b1/src/pdfviewer/PDFDocument.cpp).
- **PDF viewers with GTK interfaces**
  - Evince: [`synctex_scanner_t`](https://github.com/GNOME/evince/blob/5df2cafe10d8120caa0a1813fee9bbd5c15d506a/cut-n-paste/synctex/synctex_parser.c)
  - Zathura: [`run_synctex_forward`](https://git.pwmt.org/pwmt/zathura/-/blob/develop/zathura/main.c)

**Comment by Vectornaut** [comment]
This feature is implemented! To use it, go to *Document → Set Compilation Options* and check *Enable SyncTeX*. After the next compilation, holding *[control]* and clicking a paragraph in the PDF preview will take you to the corresponding paragraph of the source code.

We should make this feature more discoverable, since at least two people wanted it but couldn't see that it was available.
