### ISSUE TITLE
Greek Letters Won't Render

### ISSUE THREAD

**Issue by AlexMorello** [alexandervdm/gummi#172]
Dear folks, 

when entering a Greek letter such as μ the preview won't render. Any ideas? I really need a fix.

**Comment by alexandervdm** [comment]
Have you tried ```\mu```?

Also, Github is not a support forum.

**Comment by AlexMorello** [comment]
Dear Alexander, 

Thank you for your prompt response! Sorry, I got here by clicking on 'Help' -> 'User Guide'. Which is the correct support thread then? 

> Have you tried `\mu`?

I did, and to no avail. The document failed to render.

**Comment by AlexMorello** [comment]
Hello?..

**Comment by AlexMorello** [comment]
Up

**Comment by AlexMorello** [comment]
I can't submit the paper with like GAMMA and MU and whatnot all written out, man.... @alexandervdm

**Comment by cmahte** [comment]
Alex, you are hitting a TeX thing, not Gummi.  You need to seek information
about fonts in TeX, not continue to expect this program support page to
offer free training.

Google "typing math formulas in TeX"

**Comment by cmahte** [comment]
Re: view the build log on error @alexandervdm. 

Maybe instead of displaying "PDF Preview could not initialize" when an document update won't compile, automatically switch the view to the build log?  It would prompt novice users to read the log...

**Comment by AlexMorello** [comment]
@cmahte Dear Michael,

Thank you for responding so quickly! I'm not sure that's the case, though. I've tried the 'Greek' syntax suggested by Overleaf, but it won't work with Gummi.

**Comment by cmahte** [comment]
learn TeX and LaTeX.

That's been the point of all the comments besides yours.

A specific way to get \mu to work in Gummi, plain TeX and LaTeX is

$$\mu$$

But that is only for math formulas. That is, the mu will appear on its own
line, centered, and with a blank row before and after it.

TeX was originally created to provide a way to publish fancy papers about
math. It has from its earliest beta release supported Greek characters in
output. Any form of the TeX language supports greek text in this way. Gummi
isn't about how to make TeX documents, but rather how to make them more
quickly with a live preview. If you see errors on the "Build Log" pane,
that is not a Gummi issue, but the way you coded TeX or LaTeX Or Lua, or
...   It is not productive to complain about your own lack of understanding
as a program bug. It is not. If you'd looked at the build log, It would
have told you that TeX doesn't support unicode.  If you'd looked at the
build log for \mu not wrapped in $$ it provides text that turns into a
package to include if you want to directly use greek tags in paragraphs.
The build log suggests Gummi or TeX even tried to fix the problem by adding
a Single $.

I'm sure there is also a way to use Greek symbols in paragraphs, but this
is a TeX application Learning issue (that is, a USER ERROR on your part)
and not an application bug or missing feature, you need to search for the
magic string to do what you need on your own. Please do not comment on this
thread any more. Making any changes in Gummi is going to require the
process I've outlined (searching google for TeX Codes and plugins.  If you
can't get that, Gummi isn't going to work for you. The issue is closed. I
was just trying to help you find the ladder to climb instead of the cold
close you already received.

**Comment by alexandervdm** [comment]
> What's is the correct support thread then?

There is no support thread. Welcome to open source software. 

> I can't submit the paper with like GAMMAs and MUs and whatnot all written out, man.... 

How is your lack of understanding my problem, man? LaTeX is a very flexible system and there are many ways to achieve what you want. Please take an hour to learn basic LaTeX and it will all make sense. 

> @alexandervdm Also, some pics won't show up in the rendered document... Just some quotation marks...

Again you dump some vague problem and assume we have a solution.. but we still have no idea what your Gummi environment looks like or even what actual error messages you are being shown. If you are confident this is a non-PEBKAC bug, please open a new issue and don't ignore the template this time so we have some information to work with. 

> Up

> Hello?..

> Up

I am unable to offer support contracts with a 1 hour response time, but feel free to respond with the hourly rate you are willing to spend and maybe some reader will want to take you on as a client.

**Comment by AlexMorello** [comment]
> > What's is the correct support thread then?
> 
> There is no support thread. Welcome to open source software.
> 
> > I can't submit the paper with like GAMMAs and MUs and whatnot all written out, man....
> 
> How is your lack of understanding my problem, man? LaTeX is a very flexible system and there are many ways to achieve what you want. Please take an hour to learn the basics and it will all make sense.
> 
> > @alexandervdm Also, some pics won't show up in the rendered document... Just some quotation marks...
> 
> Again you dump some vague problem and assume I have a solution ready.. but I still have no idea what your Gummi environment looks like or even what actual error messages you are being shown. If you are confident this is a non-PEBKAC bug, please open a new issue and don't ignore the template this time so there is some information to work with.
> 
> > Up
> 
> > Hello?..
> 
> > Up
> 
> I am unable to offer support contracts with a 1 hour response time, but feel free to respond with the hourly rate you are willing to spend and maybe some reader will want to take you on as a client.

Sorry, didn't mean to be... well, mean, hehe. Thanks!
