### ISSUE TITLE
User Guide Broken Link

### ISSUE THREAD

**Issue by sasongko26** [alexandervdm/gummi#2]
I just installed Gummi from my repository. I clicked Help tab then User Guide, I taken to a page https://github.com/projects/gummi/wiki/UserGuide/alexandervdm/gummi that is not found. I hope this broken link fixed immediately.

**Comment by mlda065** [comment]
I'm guessing that the reason that hasn't been fixed is that there is currently no place that the link *should* point to.

As it says in [the readme](https://github.com/alexandervdm/gummi):

> The documentation, written by Guy Edwards, is still on my disk. I will get it converted to Github's wiki format as soon as I can.

**Comment by mlda065** [comment]
Ok I just had a look. That URL is defined as `C_GUMMIGUIDE` in `src/constants.h`.

That was updated to the new git wiki on 13th February. So that *should* be fixed. I don't know why the final product doesn't reflect that code change.

![code change](https://cloud.githubusercontent.com/assets/7035647/9036281/65f6b9fa-3a23-11e5-93c0-e0b8d20b844c.png)

**Comment by ajs124** [comment]
Maybe your distro ships an older version? Which repo did you install it from?

**Comment by mlda065** [comment]
I just installed it on a fresh version of Mint 17.2 Rafaela.

**Comment by alexandervdm** [comment]
I've uploaded most of the original user guide to Github, and the menu item will point towards the correct URL in the upcoming 0.6.6 release. Thanks for the report.
