### ISSUE TITLE
Move to GTK3

### ISSUE THREAD

**Issue by ghost** [alexandervdm/gummi#33]
As https://github.com/aitjcize/Gummi did.

**Comment by acz13** [comment]
Progress on this?

**Comment by keeferrourke** [comment]
Is there an update on this? Gummi is seriously awesome and https://github.com/aitjcize/Gummi makes some much needed improvements.

**Comment by alexandervdm** [comment]
Apologies about October 2016 >< 

I finally have some free time ahead of me and I've begun to review the gtk3 code. More news soon.

**Comment by hlef** [comment]
@alexandervdm any progress on the GTK3 port?

I am the Debian maintainer of Gummi. If Gummi doesn't get ported to GTK3 soon, we will have to remove it from Debian. We would really like to avoid this!

See [the Debian bug report](https://bugs.debian.org/885681) for more information. Thanks for your work!

**Comment by alexandervdm** [comment]
Hi @hlef , thanks for the heads up. I also would very much like to avoid having Gummi removed from Debian. I've been in contact with @aitjcize about porting his gtk3 work into this repository and have done some work to that end, but in all honesty my C/GTK is a little rusty so it's clear to me that doing it right will require me to sit down and focus on it for a few days. 

Since I'm not sure I'll actually be able to find the time in the short term, I hereby declare **October 1st** (2019 heh) to be my deadline. If I haven't finished the work by then, I'll pursue alternative approaches, like funding an interested student/junior programmer through some sort of bug bounty program. In any case the work should get done. 

That leaves the issue of testing. With my days as a student behind me, my current use of Gummi is limited to basic invoices and the occasional article. If any power users who preferably know (or want to learn) how to stacktrace are interested in helping out in this area, please contact me and I'll prepare test builds for your respective platforms.

**Comment by hlef** [comment]
Thanks @alexandervdm, I understand the situation.

I would truly like to help, however I am already struggling to find sufficient time for my current free software involvement. Do you have a roadmap somewhere, or a bug tracker label/milestone for the GTK3 migration?

Ideally, we would have a fully stable GTK3 port for the release of Debian Bullseye, in a bit less than two years. The short term goal (next months, end of the year) would be to have an acceptable GTK3 port, so that we can get it into Debian testing.

Thanks for your work!

**Comment by alexandervdm** [comment]
No worries, I'm making good progress already in the gtk3 branch. Currently this branch seems to run with no obvious critical problems as far as I tell after very limited testing. There are of course still a bunch of warnings/deprecations that I'll have to look into in the coming period. 

I have some ideas for new features, but no formal roadmap or anything. For this first gtk3 release I will focus on stability / retaining feature-parity with gummi-0.6.6. 

I should be able to get a test build out by the end of the month and will aim for a first release before the end of the year. Thank you for being so pro-active in maintaining Gummi. Debian (including your predecessor Daniel Stender) has always been great in that regard!

**Comment by alexandervdm** [comment]
The migration is complete and the new code seems to be running well. As expected I've not been able to do much testing though. The new stable release will be **0.8.0** to avoid any versioning conflicts with Wei-Ning's fork. 

In the meantime I'm preparing a **0.7.999** build that I'm hoping to get some eyeballs on. 
@hlef - is sid a suitable candidate repository to package this for, provided you have time of course?

**Comment by alexandervdm** [comment]
The GTK3 migration is complete and a test build is now available. If you experience any problems with it, please report a new bug. Thanks!

**Comment by hlef** [comment]
@alexandervdm sorry for my late answer, those are great news!

Sure, I will package 0.7.999 for unstable. 0.8.0 will also get in as soon as it's released.

**Comment by alexandervdm** [comment]
@hlef Great, thank you for your time and efforts! If you have any questions, feel free to contact me directly.

**Comment by hlef** [comment]
FTR, 0.7.999 entered unstable yesterday.

**Comment by alexandervdm** [comment]
Great news - thank you for your time :)

**Comment by alexandervdm** [comment]
BTW, 0.8.0-rc2 is available. Hopefully the last build before 0.8.0 release.
