### ISSUE TITLE
"Match entire word only" option not working in Find

### ISSUE THREAD

**Issue by emo916math** [alexandervdm/gummi#62]
Using the following sample document,
```
eggs and ham
egg
eggs and ham
```
place the cursor at the upper left and do a search for "egg" with the Find dialog box with the "Match entire word only" option checked. When I click the "Find" button, the dialog does nothing (i.e. it neither finds the match nor claims there are no matches).

I'm running Gummi 0.6.5 in Linux Mint 17.3.

**Comment by bobi32** [comment]
To help debugging this one, on the default file, when opening gummi, I tried to search for “the” (as it appears several times as an entire word, only one time within another word — “together” on line 14).

It turns out that, with the wholeword option toggled, only matching occurrences _before_ “together” are highligthed.

But the behavior when cycling within matches seems to be more erratic: first (let’s call it step 1), when searching from the head of file (having the cursor before `\documentclass…`), it starts cycling on the three highligthed occurrences, but stucks on the third, unable to find the next one nor propose to search from top.
However, if manually placing the cursor anywhere _after_ “together”, then the search cycles within the next occurrences, _without_ highligthting them, and when on the last one of the file, correctly proposes to search again from the top, returning to step 1.

Naturally, if I add another non-wholeword match within the file (eg theorem), search stucks on both “together” and “theorem”.

I can’t see from the code why this occurs, but I hope these thorough tests might help.

**Comment by bobi32** [comment]
I just opened a pull request that make the “Match entire word only” work as expected. I’m hoping it gets merged soon!

In the meanwhile, @emo916math, you might want to clone the following branch and build it yourself: https://github.com/bobi32/gummi/tree/wholeword
